statusdb:
    url: statusdb.server
    username: user
    password: hacktheplanet
    port: 1337

sbatch:
    extra_arg: --qos=seqver


#########################
# RUN CONFIG GENERATION #
#########################

templates:
    chipseq_template:           $HOME/opt/bcbb_config/templates/illumina-chipseq.yaml
    dna_alignonly_template:     $HOME/opt/bcbb_config/templates/dna-align.yaml
    exome_alignonly_template:   $HOME/opt/bcbb_config/templates/exome-targeted.yaml
    gatk_variant_template:      $HOME/opt/bcbb_config/templates/gatk-variant.yaml
    mirna_template:             $HOME/opt/bcbb_config/templates/mirna-bowtie.yaml
    noalign_variant_template:   $HOME/opt/bcbb_config/templates/noalign-variant.yaml
    qc_pipeline_template:       $HOME/opt/bcbb_config/templates/qc-noalign.yaml
    rnaseq_template:            $HOME/opt/bcbb_config/templates/illumina-rnaseq.yaml
    tumor_normal_template:      $HOME/opt/bcbb_config/templates/tumor-paired.yaml

method_to_pipeline_mappings:
    "150 bp insert standard DNA (Illumina TruSeq DNA)":
        - qc_pipeline_template
        - dna_alignonly_template
    "300 bp insert standard DNA (Illumina TruSeq DNA) (standard for DNA)":
        - qc_pipeline_template
        - dna_alignonly_template
    "650 bp insert standard DNA (Illumina TruSeq DNA)":
        - qc_pipeline_template
        - dna_alignonly_template
    "350 bp insert PCR-free DNA (illumina TruSeq DNA)":
        - qc_pipeline_template
        - dna_alignonly_template
    "550 bp insert PCR-free DNA (illumina TruSeq DNA)":
        - qc_pipeline_template
        - dna_alignonly_template
    "no fragmentation (Illumina TruSeq DNA)":
        - qc_pipeline_template
        - dna_alignonly_template
    "150bp insert Rubicon Thruplex":
        - qc_pipeline_template
        - dna_alignonly_template
    "180bp insert Rubicon Thruplex":
        - qc_pipeline_template
        - dna_alignonly_template
    "300bp insert Rubicon Thruplex":
        - qc_pipeline_template
        - dna_alignonly_template
    "650bp insert Rubicon Thruplex":
        - qc_pipeline_template
        - dna_alignonly_template
    "no fragmentation (Rubicon Thruplex)":
        - qc_pipeline_template
        - dna_alignonly_template
    "Stranded mRNA-seq (Illumina TruSeq RNA HT with polyA-selection)":
        - qc_pipeline_template
        - rnaseq_template
    "Stranded mRNA-seq (Illumina TruSeq RNA HT with RiboZero)":
        - qc_pipeline_template
        - rnaseq_template
    "Stranded mRNA-seq (customer has purified mRNA)":
        - qc_pipeline_template
        - rnaseq_template
    "miRNA-seq (Illumina TruSeq small RNA)":
        - qc_pipeline_template
        - mirna_template
    "Exome Sequence capture (Agilent SureSelect)":
    ## doesn't exist yet
        - qc_pipeline_template
        - exome_alignonly_template
    "Custom Sequence capture (Agilent SureSelect)":
    ## ?
        - qc_pipeline_template
        - dna_alignonly_template
    "Nextera Mate-pair (Short insert)":
        - qc_pipeline_template
    "Nextera Mate-pair (Long insert)":
        - qc_pipeline_template
    "Finished libraries by customer (10nM)":
        - qc_pipeline_template
    "Special, none of the above":
        - qc_pipeline_template

supported_genomes:
    - "hg19"
    - "mm9"
    - "rn4"
    - "saccer2"
    - "dm3"
    - "tair9"
    - "xentro2"
    - "ws210"
    - "canfam3"


#############################
# FILE COLLECTION / SORTING #
#############################

project:
    INBOX: /path/to/demux/dump/

analysis:
    # This is the name of the python class to use
    analysis_pipeline: scilifelab.bcbio.BcbioAnalysis
    analysis_launch_method: sbatch              # sbatch, command_line / default command_line
    ## not yet finalized
    #analysis_launch_host:                      # default localhost
    #    - hostname: milou.uppmax.uu.se
    #    - port: 22
    #    - user: cereal_killer
    #    - password: trashing
    # Copy files from demux structure to to-be-processed structure ($top_dir/project/sample/fcid/)
    top_dir: /path/to/analysis/top/directory
    log: /proj/a2010002/data/log
    store_dir: /proj/a2010002/archive
