# This file should be placed under $HOME/.ngiconfig/ngi_config.yaml
# or its path exported as the environment variable NGI_CONFIG


analysis:
    best_practice_analysis:
        whole_genome_reseq:
            analysis_engine: ngi_pipeline.engines.piper_ngi
    top_dir: /proj/a2014205/nobackup/NGI/analysis_ready


database:
    record_tracking_db_path: /proj/a2014205/ngi_resources/record_tracking_database_nestor.sql


environment:
    project_id: a2014205
    conda_env: ngi
    ngi_scripts_dir: /proj/a2014205/software/ngi_pipeline/scripts


logging:
    log_file: /proj/a2014205/ngi_resources/ngi_pipeline.log


piper:
    # Also can be set as an environmental variable $PIPER_QSCRIPTS_DIR
    path_to_piper_qscripts: /proj/a2014205/software/piper/qscripts
    load_modules:
        - java/sun_jdk1.7.0_25
        - R/2.15.0
    sample:
        required_autosomal_coverage: 28.4
    threads: 16


slurm:
    extra_params:
        "--qos": "seqver"


supported_genomes:
    "GRCh37": /proj/a2014205/piper_references/gatk_bundle/2.8/b37/human_g1k_v37.fasta
