# This file should be placed under $HOME/.ngiconfig/ngi_config.yaml
# or its path exported as the environment variable NGI_CONFIG

sbatch:

database:
    record_tracking_db_path: /$HOME/.ngipipeline/record_tracking_database
    #record_tracking_db_path: /proj/a2010002/nobackup/NGI/database/record_tracking_database

environment:
    project_id: a2010002
    #extra_slurm_params:
    #    - "--qos=seqver"
    ngi_scripts_dir: $HOME/ngi_pipeline/scripts
    conda_env: ngi

piper:
    # Also can be set as an environmental variable $PIPER_QSCRIPTS_DIR
    path_to_piper_qscripts: /proj/a2010002/software/piper/qscripts
    load_modules:
        - java/sun_jdk1.7.0_25
        - R/2.15.0


qc:
    fastqc:
        path: /sw/apps/bioinfo/fastqc/0.11.2/nestor/fastqc
    fastq_screen:
        path: /sw/apps/bioinfo/fastq_screen/0.4.3/nestor/bin/fastq_screen
        path_to_bowtie2: /sw/apps/bioinfo/bowtie2/2.0.2/nestor/bowtie2
        path_to_config: 

supported_genomes:
    "GRCh37": "/proj/a2009002/piper_references/gatk_bundle/2.8/b37/human_g1k_v37.fasta"

analysis:
    workflows:
        NGI:
            analysis_engine: ngi_pipeline.engines.piper_ngi
    top_dir: /proj/a2010002/nobackup/NGI/analysis_ready
