# This file should be placed under $HOME/.ngiconfig/ngi_config.yaml
# or its path exported as the environment variable NGI_CONFIG


analysis:
    best_practice_analysis:
        whole_genome_reseq:
            analysis_engine: ngi_pipeline.engines.piper_ngi
        qc:
            analysis_engine: ngi_pipeline.engines.qc_ngi
    top_dir: /proj/a2014205/nobackup/NGI/analysis_ready


database:
    record_tracking_db_path: /proj/a2014205/ngi_resources/record_tracking_database_nestor.sql


environment:
    project_id: a2014205
    conda_env: ngi
    ngi_scripts_dir: /proj/a2014205/software/ngi_pipeline/scripts
    flowcell_inbox: /proj/a2014205/archive


logging:
    log_file: /proj/a2014205/ngi_resources/ngi_pipeline.log


paths: # Hard code paths here if you are that kind of a person
    binaries:
        #bowtie2:
        #fastqc:
        #fastq_screen:
    references:


piper:
    # Also can be set as an environmental variable $PIPER_QSCRIPTS_DIR
    path_to_piper_qscripts: /proj/a2014205/software/piper/qscripts
    load_modules:
        - java/sun_jdk1.7.0_25
        - R/2.15.0
    threads: 16
    #shell_jobrunner: Shell
    #jobNative:
    #    - arg1
    #    - arg2
    #    - arg3

qc:
    load_modules:
        - bioinfo-tools
    fastqc:
        load_modules:
            - FastQC
        threads: 16
    fastq_screen:
        config_path: "/proj/a2014205/ngi_resources/fastq_screen.nestor.conf"
        load_modules:
            - bowtie2
            - fastq_screen
        subsample_reads: 200000
        threads: 1


slurm:
    extra_params:
        "--qos": "seqver"
    cores: 16


supported_genomes:
    "GRCh37": /proj/a2014205/piper_references/gatk_bundle/2.8/b37/human_g1k_v37.fasta

test_data:
    workflows:
        whole_genome_reseq:
            remote:
                #rsync:
                #    user: funk_002
                #    remote_path: /proj/a2009002/webexport/opendata/HiSeqX_CEPH/NA10860-PCR-free-150pM/02-FASTQ/
                #    local_parent_dir: /proj/a2014205/nobackup/NGI/test_data/merge_variant_call/
                #    post_download:
                #        - "module load bioinfo-tools"
                #        - "module load seqtk"
                #        - "seqtk sample {fastq_path} 10000"
                #wget:
                #    remote_path: http://chapmanb.s3.amazonaws.com/100326_FC6107FAAXX.tar.gz
                #    local_parent_dir: /proj/a2014205/nobackup/NGI/test_data/merge_variant_call/
                #wget:
                #   remote_path: ftp://ftp-trace.ncbi.nih.gov/giab/ftp/technical/NIST_NA12878_HG001_HiSeq_300x/131219_D00360_005_BH814YADXX/Project_RM8398/Sample_U0a/U0a_CGATGT_L001_R?_001.fastq.gz
                #   local_parent_dir: 
            local_files:
                #flowcell: /proj/a2014205/nobackup/NGI/test_data/whole_genome_reseq/100326_D00000_000_A6107FAAXX
                project: /proj/a2014205/nobackup/NGI/test_data/whole_genome_reseq/P1234
                vcf: /proj/a2014205/nobackup/NGI/test_data/whole_genome_reseq/04-vcf/
            #charon_base_url: http://charon-dev.scilifelab.se
